// terraformRunner.js — spawns terraform commands and streams logs back to the panel.
// State management: S3 remote backend per project (bucket key = <projectId>/<module>/).
// Each run writes a backend_override.tf before terraform init so state is fully isolated.

const { spawn, execSync } = require("child_process");
const fs   = require("fs");
const path = require("path");

// In-memory store of active runs: runId → { logs, status, outputs, error }
const runs = new Map();

// ── Cross-platform Terraform binary resolver ──
function getTerraformBin() {
  if (process.env.TF_BINARY && fs.existsSync(process.env.TF_BINARY)) {
    return process.env.TF_BINARY;
  }

  const commonLinuxPaths = [
    "/usr/local/bin/terraform",
    "/usr/bin/terraform",
    "/bin/terraform",
    "/snap/bin/terraform",
    "/home/admin/.local/bin/terraform",
    "/home/ubuntu/.local/bin/terraform"
  ];

  if (process.platform !== "win32") {
    for (const p of commonLinuxPaths) {
      if (fs.existsSync(p)) return p;
    }
    try {
      const found = execSync("which terraform", { encoding: "utf8" }).trim().split("\n")[0];
      if (found && fs.existsSync(found)) return found;
    } catch (_) {}
  } else {
    try {
      const found = execSync("where terraform", { encoding: "utf8" }).trim().split("\n")[0];
      if (found && fs.existsSync(found)) return found;
    } catch (_) {}
  }

  return "terraform";
}

// ── Folder paths relative to this file ──────────────────────────────
const INITIAL_DIR          = path.join(__dirname, "infra-initial");
const DEPLOYMENT_DIR       = path.join(__dirname, "golf-infra-terraform");
const SHARED_FOUNDATION_DIR = path.join(__dirname, "shared-foundation-terraform");

// Shared-foundation is applied ONCE for the whole platform, not per project —
// but _writeBackend()'s S3 key isolation is keyed on projectId, so we give it
// a fixed pseudo-project id to get its own dedicated, stable state key.
const SHARED_FOUNDATION_STATE_ID = "_shared-foundation";

// ── S3 backend configuration ─────────────────────────────────────────
const TF_STATE_BUCKET  = process.env.TF_STATE_BUCKET  || "benevolate-tf-state-393886308751";
const TF_LOCK_TABLE    = process.env.TF_LOCK_TABLE     || "benevolate-tf-locks";
const TF_STATE_REGION  = process.env.TF_STATE_REGION   || process.env.AWS_REGION || "us-east-1";

/**
 * Write a backend_override.tf into `folder` that points Terraform at the
 * project-scoped S3 key.  Terraform's override mechanism merges this with the
 * rest of the config at init time — no edits to main.tf needed.
 *
 * S3 key layout:
 *   <projectId>/initial/terraform.tfstate
 *   <projectId>/deployment/terraform.tfstate
 *
 * If projectId is null/undefined we write a local backend (safe for
 * one-off / legacy runs).
 */
function _writeBackend(folder, projectId, moduleLabel) {
  const backendFile = path.join(folder, "backend_override.tf");

  if (!projectId) {
    // Fall back to local state — don't override anything
    try { fs.unlinkSync(backendFile); } catch (_) {}
    return;
  }

  const key = `${projectId}/${moduleLabel}/terraform.tfstate`;

  const content = `
# AUTO-GENERATED by the CI/CD Admin platform — do not edit by hand.
# This file is re-written before every terraform init to isolate state
# per project in the shared S3 backend bucket.
terraform {
  backend "s3" {
    bucket         = "${TF_STATE_BUCKET}"
    key            = "${key}"
    region         = "${TF_STATE_REGION}"
    dynamodb_table = "${TF_LOCK_TABLE}"
    encrypt        = true
  }
}
`;
  fs.writeFileSync(backendFile, content);
}

function generateRunId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
}

/**
 * Start a terraform apply run in the background.
 * @param {string} folder   - absolute path to the terraform folder (INITIAL_DIR or DEPLOYMENT_DIR)
 * @param {object} tfvars   - key/value pairs to write as panel.auto.tfvars
 * @param {object} opts
 * @param {string} opts.projectId   - project UUID; used for S3 key isolation
 * @param {string} opts.moduleLabel - "initial" | "deployment" (default = folder basename)
 * @returns {string} runId — poll via getRun(runId)
 */
function startRun(folder, tfvars, opts = {}) {
  const runId = generateRunId();
  runs.set(runId, { logs: [], status: "running", outputs: null, error: null });
  _execute(runId, folder, tfvars, false, opts).catch(() => {});
  return runId;
}

function startDestroy(folder, tfvars, opts = {}) {
  const runId = generateRunId();
  runs.set(runId, { logs: [], status: "running", outputs: null, error: null });
  _execute(runId, folder, tfvars, true, opts).catch(() => {});
  return runId;
}

async function _execute(runId, folder, tfvars, isDestroy, opts = {}) {
  const run = runs.get(runId);
  const addLog = (line) => run.logs.push({ ts: Date.now(), line: line.trimEnd() });

  const { projectId, moduleLabel } = opts;
  const label = moduleLabel || path.basename(folder); // "infra-initial" or "golf-infra-terraform"

  try {
    // 1. Write per-project S3 backend override
    _writeBackend(folder, projectId, label);
    if (projectId) {
      addLog(`State backend: s3://${TF_STATE_BUCKET}/${projectId}/${label}/terraform.tfstate`);
    } else {
      addLog("State backend: local (no projectId supplied)");
    }

    // 2. Write terraform.auto.tfvars
    const tfvarsContent = Object.entries(tfvars)
      .filter(([, v]) => v !== undefined && v !== null && v !== "")
      .map(([k, v]) => `${k} = ${JSON.stringify(String(v))}`)
      .join("\n");
    fs.writeFileSync(path.join(folder, "panel.auto.tfvars"), tfvarsContent + "\n");

    addLog(`Working directory: ${folder}`);

    // 3. terraform init — -reconfigure migrates to the new backend on first run
    addLog("Running: terraform init -reconfigure");
    await spawnAsync("terraform", ["init", "-reconfigure", "-no-color"], folder, addLog);

    if (isDestroy) {
      addLog("Running: terraform destroy -auto-approve");
      await spawnAsync("terraform", ["apply", "-destroy", "-auto-approve", "-no-color"], folder, addLog);
      run.outputs = {};
      run.status  = "done";
      addLog("Terraform destroy completed successfully.");
    } else {
      addLog("Running: terraform apply -auto-approve");
      await spawnAsync("terraform", ["apply", "-auto-approve", "-no-color"], folder, addLog);

      // 4. Capture outputs
      addLog("Running: terraform output -json");
      const raw    = await captureStdout("terraform", ["output", "-json"], folder);
      const parsed = JSON.parse(raw || "{}");

      // Flatten: { key: { value: ... } } → { key: value }
      const outputs = {};
      for (const [k, v] of Object.entries(parsed)) {
        outputs[k] = v.value;
      }

      run.outputs = outputs;
      run.status  = "done";
      addLog("Terraform completed successfully.");
    }
  } catch (err) {
    run.status = "error";
    run.error  = err.message;
    addLog(`Failed: ${err.message}`);
  }
}

function spawnAsync(cmd, args, cwd, onLog) {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, {
      cwd,
      env: { ...process.env, TF_IN_AUTOMATION: "1", TF_CLI_ARGS: "" }
    });
    const forward = (data) => {
      data.toString().split("\n").forEach(line => {
        if (line.trim()) onLog(line);
      });
    };
    proc.stdout.on("data", forward);
    proc.stderr.on("data", forward);
    proc.on("close", code => (code === 0 ? resolve() : reject(new Error(`Exit code ${code}`))));
  });
}

function captureStdout(cmd, args, cwd) {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, { cwd });
    let out = "";
    proc.stdout.on("data", d => out += d.toString());
    proc.on("close", code => (code === 0 ? resolve(out) : reject(new Error(`Capture failed: exit ${code}`))));
  });
}

/** Get the current state of a run */
function getRun(runId) {
  return runs.get(runId) || null;
}

/**
 * Reads the shared-foundation stack's outputs directly from its Terraform
 * state (not cached — always reflects what's actually applied). Used by
 * every deployment tfvars build so projects always get the live vpc_id,
 * subnets, ecs_sg_id, and ALB references.
 *
 * Throws if the stack hasn't been applied yet (no state / empty outputs) —
 * callers should surface this as "Apply Shared Foundation Infrastructure first."
 */
async function getSharedFoundationOutputs() {
  _writeBackend(SHARED_FOUNDATION_DIR, SHARED_FOUNDATION_STATE_ID, "foundation");
  await spawnAsync("terraform", ["init", "-reconfigure", "-no-color"], SHARED_FOUNDATION_DIR, () => {});
  const raw = await captureStdout("terraform", ["output", "-json"], SHARED_FOUNDATION_DIR);
  const parsed = JSON.parse(raw || "{}");
  if (Object.keys(parsed).length === 0) {
    throw new Error("Shared foundation infrastructure has not been applied yet.");
  }
  const outputs = {};
  for (const [k, v] of Object.entries(parsed)) outputs[k] = v.value;
  return outputs;
}

/**
 * Returns the S3 URL for a project's state file (useful for displaying in the UI).
 */
function stateUrl(projectId, moduleLabel) {
  if (!projectId) return null;
  return `s3://${TF_STATE_BUCKET}/${projectId}/${moduleLabel}/terraform.tfstate`;
}

module.exports = {
  startRun, startDestroy, getRun, stateUrl,
  INITIAL_DIR, DEPLOYMENT_DIR,
  SHARED_FOUNDATION_DIR, SHARED_FOUNDATION_STATE_ID,
  getSharedFoundationOutputs
};
